import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Testing Builder.io",
  description: "Generated by builder.io",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
