/**
 * This code was generated by Builder.io.
 */
import React from "react";
import Image from "next/image";

function ButtonComponent(props: any) {
  return (
    <button className="relative shrink-0 box-border appearance-none bg-[black] text-[white] rounded text-center cursor-pointer mt-5 px-6 py-4">
      Click It!
    </button>
  );
}

export default ButtonComponent;
