/**
 * This code was generated by Builder.io.
 */
import * as React from "react";
import Image from "next/image";

const LandingPage: React.FC = () => {
  return (
    <div className="flex flex-col items-stretch relative shrink-0 box-border h-[90vh] self-stretch bg-[url(https://cdn.builder.codes/api/v1/image/assets%2FagZ9n5CUKRfbL9t6CaJOyVSK4Es2%2Fced3a5c6e7ad4d70af68111e2d37487d?width=2000&height=1000)] bg-no-repeat bg-center bg-cover mt-6 px-8 max-sm:h-[500px]">
      <div className="flex flex-col items-stretch relative shrink-0 box-border h-auto w-full max-w-[1200px] text-left m-auto pb-28 max-md:pb-20 max-sm:pb-4">
        <div className="flex flex-col items-stretch relative shrink-0 box-border w-[480px] mr-auto max-md:w-[370px] max-sm:w-[200px]">
          <div className="items-stretch relative shrink-0 box-border mt-0 h-auto text-left text-6xl text-white mr-auto max-sm:text-4xl">
            <p>Hello This is Mainkanta</p>
          </div>
          <div className="items-stretch relative shrink-0 box-border h-auto text-left text-white mt-5 max-sm:text-base">
            <p>This is Description</p>
          </div>
        </div>
      </div>
    </div>
  );
};

export default LandingPage;
